version: '3'
services:
    chickenpot-takeaway-portal:
        networks:
            - dev-vn-networks
        container_name: chickenpot-takeaway-portal
        restart: always
        image: chickenpot-takeaway-portal-img:1.0.0
        labels:
            - "traefik.enable=false"
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M 
    chickenpot-takeaway-portal-nginx:
        networks:
            - dev-vn-networks
        ports:
            - "8297:80"
        container_name: chickenpot-takeaway-portal-nginx
        restart: always
        image: nginx:latest
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - chickenpot-takeaway-portal
        labels:
            - "traefik.docker.network=dev-vn-networks"
            - "traefik.enable=true"
            - "traefik.basic.frontend.rule=Host:chickenpot-takeaway-portal.com"
            - "traefik.basic.port=80"
            - "traefik.basic.protocol=http"
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M 
networks:
  dev-vn-networks:
    external: true

