version: '3'
services:
    ibmsm-web:
        env_file: ./app/.env
        ports:
            - "8070:3000"
        networks:
            - dev-vn-networks
        container_name: ibmsm-web
        restart: always
        image: ibmsm-web-img:1.0.1
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 512M
networks:
    dev-vn-networks:
        external: true
